name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Done printing
        run: echo "Done- good bye!"
      - name: Multiple echos
        run: |
          echo "First output"
          echo "Second output"
